### ISSUE TITLE
Empty regions

### ISSUE THREAD

**Issue by Eahlstan** [canonn-science/bioforge#1]
"The Conduit" and "Kepler's Crest" are completely blank even though there are definitely species in the DB ( https://docs.google.com/spreadsheets/d/15lqZtqJk7B2qUV5Jb4tlnst6i1B7pXlAUzQnacX64Kc/edit#gid=219044904 ).

€: I think I found the bug:

"The Conduit": "#Region_15",
"Outer Orion-Perseus Conflux": "#Region_15",
...
"Kepler's Crest": "#Region_42",
"The Void": "#Region_42"

**Comment by NoFoolLikeOne** [comment]
sorted https://canonn-science.github.io/bioforge/?entryid=Bacterium%20Aurasus%20-%20Green
